# Generated by Django 2.0.3 on 2018-04-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_blog_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default=0),
        ),
    ]
