# Generated by Django 2.0.3 on 2018-05-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_classify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classify',
            name='object',
            field=models.CharField(max_length=100),
        ),
    ]
